# -*- coding: utf-8 -*-
"""Dsp_external.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7zyr9bNoO9P69gST7CbXqe2Yz3y7If5
"""





import torch
import pandas as pd
import logging
from transformers import T5Tokenizer, T5ForConditionalGeneration
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from typing import Dict, List
from google.colab import drive

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.INFO)

import re

# Preprocessing function for tweets
def preprocess_tweet(text: str) -> str:
    # Convert to lowercase
    text = text.lower()
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove mentions and hashtags
    text = re.sub(r'@\w+|\#', '', text)
    # Remove special characters and emojis
    text = re.sub(r'[^\w\s]', '', text)  # Keeps only words and spaces
    # Remove extra whitespace
    text = ' '.join(text.split())
    # Expand basic contractions (optional, simple approach)
    text = text.replace("don't", "do not").replace("won't", "will not").replace("can't", "cannot")
    return text







!pip install transformers
import torch
import pandas as pd
import logging
from transformers import T5Tokenizer, T5ForConditionalGeneration
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from typing import Dict, List
from google.colab import drive
# Load model and tokenizer
model_name = "google/flan-t5-base"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)



def detect_stance(x: str, t: str, prompt: str, decoding_strategy: str = "greedy") -> str:
    # Preprocess the tweet
    x_cleaned = preprocess_tweet(x)
    input_text = prompt.format(x=x_cleaned, t=t)
    input_ids = tokenizer.encode(input_text, return_tensors="pt", max_length=128, truncation=True).to(device)

    if decoding_strategy == "greedy":
        outputs = model.generate(input_ids, max_length=16, do_sample=False)
    else:  # beam search
        outputs = model.generate(
            input_ids,
            max_length=16,
            num_beams=4,               # More beams = better quality (optional tweak)
            early_stopping=True,
            num_return_sequences=1     # Only keep best beam
        )

    pred = tokenizer.decode(outputs[0], skip_special_tokens=True).strip().upper()

    # Normalize prediction to standard labels
    if "FAVOR" in pred:
        return "FAVOR"
    elif "AGAINST" in pred:
        return "AGAINST"
    elif "NEUTRAL" in pred:
        return "NEUTRAL"
    else:
        return "NEUTRAL"  # Fallback





data = pd.read_csv("/content/processed1_test.csv")
data.shape

datasets={'data':'/content/processed1_test.csv'} # divided datasets for each.

from sklearn.metrics import accuracy_score

# Evaluate on all test datasets (zero-shot testing)
def evaluate_on_datasets(prompts: List[str], datasets: Dict[str, str], decoding_strategy: str = "greedy"):
    results = {}
    for dataset_name, path in datasets.items():
        test_df = pd.read_csv(path)
        true_labels = test_df['Stance'].tolist()
        all_predictions = {prompt: [] for prompt in prompts}

        for x, t in zip(test_df['Tweet'], test_df['Target']):
            for prompt in prompts:
                pred = detect_stance(x, t, prompt, decoding_strategy)
                all_predictions[prompt].append(pred)

        # Calculate performance metrics without accuracy
        for prompt, predictions in all_predictions.items():
            report = classification_report(true_labels, predictions, output_dict=True, labels=["FAVOR", "AGAINST", "NEUTRAL"])
            results[f"{dataset_name}{prompt[:50]}...{decoding_strategy}"] = {
                "precision": report["weighted avg"]["precision"],
                "recall": report["weighted avg"]["recall"],
                "f1": report["weighted avg"]["f1-score"],
                "macro_f1": report["macro avg"]["f1-score"],
                "micro_f1": report["micro avg"]["f1-score"],
                "weighted_f1": report["weighted avg"]["f1-score"],
                "accuracy": accuracy_score(true_labels, predictions)
            }
            # Generate confusion matrix visualization
            cm = confusion_matrix(true_labels, predictions, labels=["FAVOR", "AGAINST", "NEUTRAL"])
            plt.figure(figsize=(4, 4))
            sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
            plt.title(f"Confusion Matrix - {dataset_name} - {prompt[:50]}... ({decoding_strategy})")
            plt.ylabel('True Label')
            plt.xlabel('Predicted Label')
            plt.savefig(f"confusion_matrix_{dataset_name}{prompt[:10]}{decoding_strategy}.png")
            plt.close()
    return results

# Define prompts (enhanced with examples, FlanT5-XXL paper, Section 3.2)
prompts = [
    f"Classify the stance of the text '{{x}}' on the topic '{{t}}' as FAVOR, AGAINST, or NEUTRAL. Example: 'i support taxes' → FAVOR.",
    f"Determine the sentiment in '{{x}}' about '{{t}}'. If positive, FAVOR; if negative, AGAINST; if neutral/ambiguous, NEUTRAL. Example: 'taxes are okay' → NEUTRAL. Classify as FAVOR, AGAINST, or NEUTRAL.",
    f"Assess if '{{x}}' supports, opposes, or is neutral toward '{{t}}'. Example: 'against new laws' → AGAINST. If unclear, NEUTRAL. Classify as FAVOR, AGAINST, or NEUTRAL.",
    f"Evaluate '{{x}}' as fact, opinion, or neutral about '{{t}}'. Example: 'facts show support' → FAVOR. Neutral statements → NEUTRAL. Classify as FAVOR, AGAINST, or NEUTRAL.",
    f"Analyze tone and logic of '{{x}}' regarding '{{t}}'. Example: 'mixed views on policy' → NEUTRAL. Classify as FAVOR, AGAINST, or NEUTRAL."]




# Evaluate with beam search (reduced beams for memory)
results_beam = evaluate_on_datasets(prompts, datasets, decoding_strategy="beam")
results_greedy = evaluate_on_datasets(prompts, datasets, decoding_strategy="greedy")

# Combine results
results = {**results_greedy,**results_beam}

# Print results including accuracy
for key, value in results.items():
    print(f"\nDataset/Prompt/Decoding: {key}")
    for metric, score in value.items():
        print(f"{metric}: {score:.4f}")

# Save results to CSV for documentation
results_df = pd.DataFrame(results).T
results_df.to_csv("evaluation_results_processed1M_beam.csv")

# Optional: Generate precision-recall plot (simplified for Colab)
plt.figure(figsize=(6, 4))
datasets = list(datasets.keys())
metrics = ["precision", "recall","accuracy"]
for ds in datasets:
    for prompt_idx, prompt in enumerate(prompts):
        for dec_idx, dec in enumerate(["greedy", "beam"]):
            data = [results[f"{ds}{prompt[:50]}...{dec}"][m] for m in metrics]
            plt.bar(np.arange(len(metrics)) + (prompt_idx * 0.2) - 0.4 + (dec_idx * 0.1), data, width=0.1, label=f"{ds} - Prompt {prompt_idx+1} ({dec})")
plt.xlabel("Metric")
plt.ylabel("Score")
plt.title("Precision vs Recall Across Datasets and Decoding")
plt.xticks(np.arange(len(metrics)), metrics)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig("precision_recall_plot.png")
plt.close()

# Save results to CSV for documentation
results_df = pd.DataFrame(results).T
results_df.to_csv("evaluation_results_processed1.csv")

# Save results to CSV for documentation
results_df = pd.DataFrame(results).T
results_df.to_csv("evaluation_results_processed1.csv")

# Optional: Generate precision-recall plot (simplified for Colab)
plt.figure(figsize=(6, 4))
datasets = list(datasets.keys())
metrics = ["precision", "recall","accuracy"]
for ds in datasets:
    for prompt_idx, prompt in enumerate(prompts):
        for dec_idx, dec in enumerate(["greedy", "beam"]):
            data = [results[f"{ds}{prompt[:50]}...{dec}"][m] for m in metrics]
            plt.bar(np.arange(len(metrics)) + (prompt_idx * 0.2) - 0.4 + (dec_idx * 0.1), data, width=0.1, label=f"{ds} - Prompt {prompt_idx+1} ({dec})")
plt.xlabel("Metric")
plt.ylabel("Score")
plt.title("Precision vs Recall Across Datasets and Decoding")
plt.xticks(np.arange(len(metrics)), metrics)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig("precision_recall_plot.png")
plt.close()

